import { KeyBindInfo } from "../type/general";

export const chromeDefaultKeyBind: { [key: string]: KeyBindInfo } = {
  "meta+a": {
    id: "meta+a",
    type: "browserDefault",
    name: "Select all",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+n": {
    id: "meta+n",
    type: "browserDefault",
    name: "Open a new window",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+n": {
    id: "meta+shift+n",
    type: "browserDefault",
    name: "Open a new window in Incognito mode",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+t": {
    id: "meta+t",
    type: "browserDefault",
    name: "Open a new tab, and jump to it",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+t": {
    id: "meta+shift+t",
    type: "browserDefault",
    name: "Reopen previously closed tabs in the order they were closed",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+option+arrowRight": {
    id: "meta+option+arrowRight",
    type: "browserDefault",
    name: "Jump to the next open tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+option+arrowleft": {
    id: "meta+option+arrowleft",
    type: "browserDefault",
    name: "Jump to the previous open tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+1": {
    id: "meta+1",
    type: "browserDefault",
    name: "Jump to tab 1",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+2": {
    id: "meta+2",
    type: "browserDefault",
    name: "Jump to tab 2",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+3": {
    id: "meta+3",
    type: "browserDefault",
    name: "Jump to tab 3",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+4": {
    id: "meta+4",
    type: "browserDefault",
    name: "Jump to tab 4",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+5": {
    id: "meta+5",
    type: "browserDefault",
    name: "Jump to tab 5",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+6": {
    id: "meta+6",
    type: "browserDefault",
    name: "Jump to tab 6",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+7": {
    id: "meta+4",
    type: "browserDefault",
    name: "Jump to tab 7",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+8": {
    id: "meta+8",
    type: "browserDefault",
    name: "Jump to tab 8",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+9": {
    id: "meta+9",
    type: "browserDefault",
    name: "Jump to tab last tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+arrowRight": {
    id: "meta+arrowRight",
    type: "browserDefault",
    name: "Open the next page in your browsing history for the current tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+BracketRight": {
    id: "meta+BracketRight",
    type: "browserDefault",
    name: "Open the next page in your browsing history for the current tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+arrowleft": {
    id: "meta+arrowleft",
    type: "browserDefault",
    name: "Open the previous page in your browsing history for the current tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+BracketLeft": {
    id: "meta+BracketLeft",
    type: "browserDefault",
    name: "Open the previous page in your browsing history for the current tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+w": {
    id: "meta+w",
    type: "browserDefault",
    name: "Close the current tab or pop-up",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+w": {
    id: "meta+shift+w",
    type: "browserDefault",
    name: "Close the current window",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+m": {
    id: "meta+m",
    type: "browserDefault",
    name: "Minimize the window",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+h": {
    id: "meta+h",
    type: "browserDefault",
    name: "Hkeybinde Google Chrome",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+q": {
    id: "meta+q",
    type: "browserDefault",
    name: "Quit Google Chrome",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+b": {
    id: "meta+shift+b",
    type: "browserDefault",
    name: "Show or hkeybinde the Bookmarks Bar",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+option+b": {
    id: "meta+h",
    type: "browserDefault",
    name: "Open the Bookmark Manager",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+,": {
    id: "meta+,",
    type: "browserDefault",
    name: "Open the Settings page in a new tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+y": {
    id: "meta+y",
    type: "browserDefault",
    name: "Open the History page in a new tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+j": {
    id: "meta+shift+j",
    type: "browserDefault",
    name: "Open the Downloads page in a new tab",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+f": {
    id: "meta+f",
    type: "browserDefault",
    name: "Open the Find Bar to search the current page",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+g": {
    id: "meta+g",
    type: "browserDefault",
    name: "Jump to the next match to your Find Bar search",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+f": {
    id: "meta+shift+f",
    type: "browserDefault",
    name: "Jump to the previous match to your Find Bar search",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+e": {
    id: "meta+e",
    type: "browserDefault",
    name: "When Find Bar is open, search for selected text",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: true,
    condition: "When Find Bar is open",
  },
  "meta+option+i": {
    id: "meta+option+i",
    type: "browserDefault",
    name: "Open Developer Tools",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+Delete": {
    id: "meta+shift+Delete",
    type: "browserDefault",
    name: "Open the Clear Browsing Data Options",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+m": {
    id: "meta+shift+m",
    type: "browserDefault",
    name: "Log in as a different user, browse as a Guest, or access payment and password info",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  F2: {
    id: "F2",
    type: "browserDefault",
    name: "Jump to the main menu bar",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+option+arrowUp": {
    id: "meta+option+arrowUp",
    type: "browserDefault",
    name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+option+arrowDown": {
    id: "meta+option+arrowDown",
    type: "browserDefault",
    name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+option+i": {
    id: "meta+shift+option+i",
    type: "browserDefault",
    name: "Open a feedback form",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  F7: {
    id: "F7",
    type: "browserDefault",
    name: "Turn on caret browsing",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
  "meta+shift+option+a": {
    id: "meta+shift+option+a",
    type: "browserDefault",
    name: "Focus on inactive dialogs",
    platform: "mac",
    browser: "chrome",
    capturable: false,
    conditional: false,
  },
};

type NestedKeyBind = {
  [key: string]: { [key: string]: KeyBindInfo };
};

export const chromeDefaultKeyBindNested = (): NestedKeyBind => {
  return {
    meta: {
      "meta+a": {
        id: "meta+a",
        type: "browserDefault",
        name: "Select all",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+e": {
        id: "meta+e",
        type: "browserDefault",
        name: "When Find Bar is open, search for selected text",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: true,
        condition: "When Find Bar is open",
      },
      "meta+f": {
        id: "meta+f",
        type: "browserDefault",
        name: "Open the Find Bar to search the current page",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+g": {
        id: "meta+g",
        type: "browserDefault",
        name: "Jump to the next match to your Find Bar search",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+h": {
        id: "meta+h",
        type: "browserDefault",
        name: "Hkeybinde Google Chrome",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+m": {
        id: "meta+m",
        type: "browserDefault",
        name: "Minimize the window",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+n": {
        id: "meta+n",
        type: "browserDefault",
        name: "Open a new window",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+q": {
        id: "meta+q",
        type: "browserDefault",
        name: "Quit Google Chrome",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+t": {
        id: "meta+t",
        type: "browserDefault",
        name: "Open a new tab, and jump to it",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+w": {
        id: "meta+w",
        type: "browserDefault",
        name: "Close the current tab or pop-up",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+y": {
        id: "meta+y",
        type: "browserDefault",
        name: "Open the History page in a new tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+1": {
        id: "meta+1",
        type: "browserDefault",
        name: "Jump to tab 1",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+2": {
        id: "meta+2",
        type: "browserDefault",
        name: "Jump to tab 2",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+3": {
        id: "meta+3",
        type: "browserDefault",
        name: "Jump to tab 3",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+4": {
        id: "meta+4",
        type: "browserDefault",
        name: "Jump to tab 4",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+5": {
        id: "meta+5",
        type: "browserDefault",
        name: "Jump to tab 5",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+6": {
        id: "meta+6",
        type: "browserDefault",
        name: "Jump to tab 6",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+7": {
        id: "meta+4",
        type: "browserDefault",
        name: "Jump to tab 7",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+8": {
        id: "meta+8",
        type: "browserDefault",
        name: "Jump to tab 8",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+9": {
        id: "meta+9",
        type: "browserDefault",
        name: "Jump to tab last tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+arrowRight": {
        id: "meta+arrowRight",
        type: "browserDefault",
        name: "Open the next page in your browsing history for the current tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+BracketRight": {
        id: "meta+BracketRight",
        type: "browserDefault",
        name: "Open the next page in your browsing history for the current tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+arrowleft": {
        id: "meta+arrowleft",
        type: "browserDefault",
        name: "Open the previous page in your browsing history for the current tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+BracketLeft": {
        id: "meta+BracketLeft",
        type: "browserDefault",
        name: "Open the previous page in your browsing history for the current tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+,": {
        id: "meta+,",
        type: "browserDefault",
        name: "Open the Settings page in a new tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
    },
    "meta+shift": {
      "meta+shift+b": {
        id: "meta+shift+b",
        type: "browserDefault",
        name: "Show or hkeybinde the Bookmarks Bar",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+f": {
        id: "meta+shift+f",
        type: "browserDefault",
        name: "Jump to the previous match to your Find Bar search",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+option+i": {
        id: "meta+option+i",
        type: "browserDefault",
        name: "Open Developer Tools",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+j": {
        id: "meta+shift+j",
        type: "browserDefault",
        name: "Open the Downloads page in a new tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+m": {
        id: "meta+shift+m",
        type: "browserDefault",
        name: "Log in as a different user, browse as a Guest, or access payment and password info",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+n": {
        id: "meta+shift+n",
        type: "browserDefault",
        name: "Open a new window in Incognito mode",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+t": {
        id: "meta+shift+t",
        type: "browserDefault",
        name: "Reopen previously closed tabs in the order they were closed",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+w": {
        id: "meta+shift+w",
        type: "browserDefault",
        name: "Close the current window",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+Delete": {
        id: "meta+shift+Delete",
        type: "browserDefault",
        name: "Open the Clear Browsing Data Options",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
    },
    "meta+option": {
      "meta+option+b": {
        id: "meta+h",
        type: "browserDefault",
        name: "Open the Bookmark Manager",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+option+i": {
        id: "meta+option+i",
        type: "browserDefault",
        name: "Open Developer Tools",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+option+arrowRight": {
        id: "meta+option+arrowRight",
        type: "browserDefault",
        name: "Jump to the next open tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+option+arrowleft": {
        id: "meta+option+arrowleft",
        type: "browserDefault",
        name: "Jump to the previous open tab",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+option+arrowUp": {
        id: "meta+option+arrowUp",
        type: "browserDefault",
        name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+option+arrowDown": {
        id: "meta+option+arrowDown",
        type: "browserDefault",
        name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
    },
    "meta+shift+option": {
      "meta+shift+option+a": {
        id: "meta+shift+option+a",
        type: "browserDefault",
        name: "Focus on inactive dialogs",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      "meta+shift+option+i": {
        id: "meta+shift+option+i",
        type: "browserDefault",
        name: "Open a feedback form",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
    },
    others: {
      F2: {
        id: "F2",
        type: "browserDefault",
        name: "Jump to the main menu bar",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
      F7: {
        id: "F7",
        type: "browserDefault",
        name: "Turn on caret browsing",
        platform: "mac",
        browser: "chrome",
        capturable: false,
        conditional: false,
      },
    },
  };
};

type NestedKeyBindList = {
  [key: string]: KeyBindInfo[];
};

export const chromeDefaultKeyBindNestedList: NestedKeyBindList = {
  meta: [
    {
      id: "meta+a",
      type: "browserDefault",
      name: "Select all",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+e",
      type: "browserDefault",
      name: "When Find Bar is open, search for selected text",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: true,
      condition: "When Find Bar is open",
    },
    {
      id: "meta+f",
      type: "browserDefault",
      name: "Open the Find Bar to search the current page",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+g",
      type: "browserDefault",
      name: "Jump to the next match to your Find Bar search",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+h",
      type: "browserDefault",
      name: "Hkeybinde Google Chrome",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+m",
      type: "browserDefault",
      name: "Minimize the window",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+n",
      type: "browserDefault",
      name: "Open a new window",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+q",
      type: "browserDefault",
      name: "Quit Google Chrome",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+t",
      type: "browserDefault",
      name: "Open a new tab, and jump to it",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+w",
      type: "browserDefault",
      name: "Close the current tab or pop-up",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+y",
      type: "browserDefault",
      name: "Open the History page in a new tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+1",
      type: "browserDefault",
      name: "Jump to tab 1",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+2",
      type: "browserDefault",
      name: "Jump to tab 2",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+3",
      type: "browserDefault",
      name: "Jump to tab 3",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+4",
      type: "browserDefault",
      name: "Jump to tab 4",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+5",
      type: "browserDefault",
      name: "Jump to tab 5",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+6",
      type: "browserDefault",
      name: "Jump to tab 6",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+4",
      type: "browserDefault",
      name: "Jump to tab 7",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+8",
      type: "browserDefault",
      name: "Jump to tab 8",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+9",
      type: "browserDefault",
      name: "Jump to tab last tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+arrowRight",
      type: "browserDefault",
      name: "Open the next page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+BracketRight",
      type: "browserDefault",
      name: "Open the next page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+arrowleft",
      type: "browserDefault",
      name: "Open the previous page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+BracketLeft",
      type: "browserDefault",
      name: "Open the previous page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+,",
      type: "browserDefault",
      name: "Open the Settings page in a new tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
  ],
  "meta+shift": [
    {
      id: "meta+shift+b",
      type: "browserDefault",
      name: "Show or hkeybinde the Bookmarks Bar",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+f",
      type: "browserDefault",
      name: "Jump to the previous match to your Find Bar search",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+option+i",
      type: "browserDefault",
      name: "Open Developer Tools",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+j",
      type: "browserDefault",
      name: "Open the Downloads page in a new tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+m",
      type: "browserDefault",
      name: "Log in as a different user, browse as a Guest, or access payment and password info",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+n",
      type: "browserDefault",
      name: "Open a new window in Incognito mode",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+t",
      type: "browserDefault",
      name: "Reopen previously closed tabs in the order they were closed",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+w",
      type: "browserDefault",
      name: "Close the current window",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+Delete",
      type: "browserDefault",
      name: "Open the Clear Browsing Data Options",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
  ],
  "meta+option": [
    {
      id: "meta+h",
      type: "browserDefault",
      name: "Open the Bookmark Manager",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+option+i",
      type: "browserDefault",
      name: "Open Developer Tools",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+option+arrowRight",
      type: "browserDefault",
      name: "Jump to the next open tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+option+arrowleft",
      type: "browserDefault",
      name: "Jump to the previous open tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+option+arrowUp",
      type: "browserDefault",
      name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+option+arrowDown",
      type: "browserDefault",
      name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
  ],
  "meta+shift+option": [
    {
      id: "meta+shift+option+a",
      type: "browserDefault",
      name: "Focus on inactive dialogs",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "meta+shift+option+i",
      type: "browserDefault",
      name: "Open a feedback form",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
  ],
  others: [
    {
      id: "F2",
      type: "browserDefault",
      name: "Jump to the main menu bar",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    {
      id: "F7",
      type: "browserDefault",
      name: "Turn on caret browsing",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
  ],
};
