import { KeyBindInfo } from "../type/general";

export const chromeDefaultKeyBind = (): { [key: string]: KeyBindInfo } => {
  return {
    "Meta+n": {
      id: "Meta+n",
      name: "Open a new window",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+n": {
      id: "Meta+Shift+n",
      name: "Open a new window in Incognito mode",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+t": {
      id: "Meta+t",
      name: "Open a new tab, and jump to it",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+t": {
      id: "Meta+Shift+t",
      name: "Reopen previously closed tabs in the order they were closed",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Option+ArrowRight": {
      id: "Meta+Option+ArrowRight",
      name: "Jump to the next open tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Option+ArrowLeft": {
      id: "Meta+Option+ArrowLeft",
      name: "Jump to the previous open tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+1": {
      id: "Meta+1",
      name: "Jump to tab 1",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+2": {
      id: "Meta+2",
      name: "Jump to tab 2",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+3": {
      id: "Meta+3",
      name: "Jump to tab 3",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+4": {
      id: "Meta+4",
      name: "Jump to tab 4",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+5": {
      id: "Meta+5",
      name: "Jump to tab 5",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+6": {
      id: "Meta+6",
      name: "Jump to tab 6",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+7": {
      id: "Meta+4",
      name: "Jump to tab 7",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+8": {
      id: "Meta+8",
      name: "Jump to tab 8",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+9": {
      id: "Meta+9",
      name: "Jump to tab last tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+ArrowRight": {
      id: "Meta+ArrowRight",
      name: "Open the next page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+BracketRight": {
      id: "Meta+BracketRight",
      name: "Open the next page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+ArrowLeft": {
      id: "Meta+ArrowLeft",
      name: "Open the previous page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+BracketLeft": {
      id: "Meta+BracketLeft",
      name: "Open the previous page in your browsing history for the current tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+w": {
      id: "Meta+w",
      name: "Close the current tab or pop-up",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+w": {
      id: "Meta+Shift+w",
      name: "Close the current window",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+m": {
      id: "Meta+m",
      name: "Minimize the window",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+h": {
      id: "Meta+h",
      name: "Hide Google Chrome",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+q": {
      id: "Meta+q",
      name: "Quit Google Chrome",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+b": {
      id: "Meta+Shift+b",
      name: "Show or hide the Bookmarks Bar",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Option+b": {
      id: "Meta+h",
      name: "Open the Bookmark Manager",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+,": {
      id: "Meta+,",
      name: "Open the Settings page in a new tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+y": {
      id: "Meta+y",
      name: "Open the History page in a new tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+j": {
      id: "Meta+Shift+j",
      name: "Open the Downloads page in a new tab",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+f": {
      id: "Meta+f",
      name: "Open the Find Bar to search the current page",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+g": {
      id: "Meta+g",
      name: "Jump to the next match to your Find Bar search",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+f": {
      id: "Meta+Shift+f",
      name: "Jump to the previous match to your Find Bar search",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+e": {
      id: "Meta+e",
      name: "When Find Bar is open, search for selected text",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: true,
      condition: "When Find Bar is open",
    },
    "Meta+Option+i": {
      id: "Meta+Option+i",
      name: "Open Developer Tools",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+Delete": {
      id: "Meta+Shift+Delete",
      name: "Open the Clear Browsing Data options",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+m": {
      id: "Meta+Shift+m",
      name: "Log in as a different user, browse as a Guest, or access payment and password info",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    F2: {
      id: "F2",
      name: "Jump to the main menu bar",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Option+ArrowUp": {
      id: "Meta+Option+ArrowUp",
      name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Option+ArrowDown": {
      id: "Meta+Option+ArrowDown",
      name: "Cycle focus to unfocused dialog (if showing) and all toolbars",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+Option+i": {
      id: "Meta+Shift+Option+i",
      name: "Open a feedback form",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    F7: {
      id: "F7",
      name: "Turn on caret browsing",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
    "Meta+Shift+Option+a": {
      id: "Meta+Shift+Option+a",
      name: "Focus on inactive dialogs",
      platform: "mac",
      browser: "chrome",
      capturable: false,
      conditional: false,
    },
  };
};
